scheduled:
  cron:
    searchTop3ByViews: "*/30 * * * * *"
    searchTop3ByLikes: "*/30 * * * * *"
spring:
  application:
    name: cache
  datasource:
    url: jdbc:h2:mem:local;NON_KEYWORDS=USER
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true